#!/usr/bin/env bash

DOCKER_TAG='graphql-faker'

cd "${0%/*}"

docker build \
       -t ${DOCKER_TAG} \
       ./node_modules/graphql-faker

docker run -ti \
       -p 9002:9002 \
       -v $(pwd)/types.graphql:/types.graphql \
       ${DOCKER_TAG} \
       /types.graphql
